package vocab

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Counter is the abstract token counter the generator depends on. The
// production implementation is internal/ledger.NewCounter (cl100k_base);
// tests can pass a stub.
type Counter interface {
	Count(s string) int
}

// TokenizerName names the tokenizer used to produce token counts.
// Mirrors internal/ledger.TokenizerName but kept local to avoid a
// reverse dependency.
const TokenizerName = "cl100k_base"

// Generate builds the full inventory from repoRoot, using counter for
// token counts. Categories are populated in the canonical order; an
// empty Sites slice in a returned Entry is fine (verbs/flags/enums are
// imported from a registry and have no scattered source sites).
func Generate(repoRoot string, counter Counter) (*Inventory, error) {
	if counter == nil {
		return nil, fmt.Errorf("vocab.Generate: nil counter")
	}

	inv := &Inventory{
		GeneratedBy: "cmd/ashvocab (ASH-102)",
		Tokenizer:   TokenizerName,
		Categories:  make(map[string][]Entry),
	}

	verbs, flags, enums := extractFromHelpRegistry(counter)
	inv.Categories[CategoryVerbs] = verbs
	inv.Categories[CategoryFlags] = flags
	inv.Categories[CategoryEnums] = enums
	inv.Categories[CategoryStatus] = extractStatus(counter)

	errs, err := extractErrors(repoRoot, counter)
	if err != nil {
		return nil, fmt.Errorf("extract errors: %w", err)
	}
	inv.Categories[CategoryErrors] = errs

	headers, labels, err := extractLiterals(repoRoot, counter)
	if err != nil {
		return nil, fmt.Errorf("extract literals: %w", err)
	}
	inv.Categories[CategoryHeaders] = headers
	inv.Categories[CategoryLabels] = labels

	return inv, nil
}

// MarshalJSON renders the inventory as deterministic, pretty-printed
// JSON. CI lint diffs this byte-for-byte against the checked-in artifact.
func (inv *Inventory) MarshalJSONIndent() ([]byte, error) {
	return json.MarshalIndent(inv, "", "  ")
}

// Markdown renders the inventory as a human-readable Markdown document.
// Section ordering matches Categories.
func (inv *Inventory) Markdown() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# ash vocabulary inventory\n\n")
	fmt.Fprintf(&b, "Generated by `%s`. Tokenizer: `%s`.\n\n", inv.GeneratedBy, inv.Tokenizer)
	fmt.Fprintf(&b, "This file is regenerated by `make vocab`; CI runs `make vocab-check` to fail on drift. Do not edit by hand.\n\n")
	fmt.Fprintf(&b, "## Summary\n\n")
	fmt.Fprintf(&b, "| category | entries | top entry | top toks |\n")
	fmt.Fprintf(&b, "|---|---:|---|---:|\n")
	for _, cat := range Categories {
		entries := inv.Categories[cat]
		top := "—"
		topTok := 0
		if len(entries) > 0 {
			top = "`" + entries[0].Literal + "`"
			topTok = entries[0].Tokens
		}
		fmt.Fprintf(&b, "| %s | %d | %s | %d |\n", cat, len(entries), top, topTok)
	}
	b.WriteByte('\n')

	for _, cat := range Categories {
		entries := inv.Categories[cat]
		fmt.Fprintf(&b, "## %s (%d)\n\n", cat, len(entries))
		if len(entries) == 0 {
			b.WriteString("_(none)_\n\n")
			continue
		}
		writeCategoryTable(&b, cat, entries)
		b.WriteByte('\n')
	}

	// Frozen footer to keep deterministic output across runs. We
	// deliberately do *not* include a timestamp — the artifact is
	// content-addressed by the source tree, and a timestamp would
	// cause CI lint to fail on every regen.
	_ = time.Time{}
	return b.String()
}

func writeCategoryTable(b *strings.Builder, cat string, entries []Entry) {
	switch cat {
	case CategoryErrors:
		fmt.Fprintf(b, "| code | toks | sites | hint? | computed? |\n")
		fmt.Fprintf(b, "|---|---:|---:|:---:|:---:|\n")
		for _, e := range entries {
			hint := ""
			if len(e.Hints) > 0 {
				hint = "✓"
			}
			computed := ""
			if e.Computed {
				computed = "✓"
			}
			fmt.Fprintf(b, "| `%s` | %d | %d | %s | %s |\n",
				e.Literal, e.Tokens, len(e.Sites), hint, computed)
		}
	case CategoryHeaders, CategoryLabels:
		fmt.Fprintf(b, "| literal | toks | sites |\n")
		fmt.Fprintf(b, "|---|---:|---:|\n")
		for _, e := range entries {
			fmt.Fprintf(b, "| `%s` | %d | %d |\n",
				escapeMD(e.Literal), e.Tokens, len(e.Sites))
		}
	case CategoryVerbs:
		fmt.Fprintf(b, "| verb | toks |\n")
		fmt.Fprintf(b, "|---|---:|\n")
		for _, e := range entries {
			fmt.Fprintf(b, "| `%s` | %d |\n", e.Literal, e.Tokens)
		}
	case CategoryFlags:
		fmt.Fprintf(b, "| flag | toks | used by |\n")
		fmt.Fprintf(b, "|---|---:|---|\n")
		for _, e := range entries {
			fmt.Fprintf(b, "| `%s` | %d | %s |\n", e.Literal, e.Tokens, e.Context)
		}
	case CategoryEnums, CategoryStatus:
		fmt.Fprintf(b, "| value | toks | context |\n")
		fmt.Fprintf(b, "|---|---:|---|\n")
		for _, e := range entries {
			fmt.Fprintf(b, "| `%s` | %d | %s |\n", e.Literal, e.Tokens, e.Context)
		}
	}
}

// escapeMD escapes the few markdown-sensitive characters that show up
// in pretty labels. Pipe characters break tables; backticks break the
// code-span wrapping. We don't need full markdown escaping — just enough
// for tables.
func escapeMD(s string) string {
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}
